# Generated by Django 4.1.6 on 2023-03-31 16:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 31, 16, 23, 21, 877137, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
