# Generated by Django 4.1.6 on 2023-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imgAddress',
            field=models.CharField(max_length=1000),
        ),
    ]
